# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/cord/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/cord/test/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/cord/test/compile/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/cord/test/fuzz/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/cord/test/headers/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/cord/test/run/CMakeLists.txt))

/Users/hotnow/TESTTHINGS/cpp/fost/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.12.3/bin/cmake -H/Users/hotnow/TESTTHINGS/cpp/src -B/Users/hotnow/TESTTHINGS/cpp/fost
