# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/json-schema/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/json-schema/json-schema-validator/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/json-schema/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/json-schema/test/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/json-schema/test/checks/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/json-schema/test/headers/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/json-schema/test/testsuite-v7/CMakeLists.txt))

/Users/hotnow/TESTTHINGS/cpp/fost/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.12.3/bin/cmake -H/Users/hotnow/TESTTHINGS/cpp/src -B/Users/hotnow/TESTTHINGS/cpp/fost
