# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/base/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/base/Cpp/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/base/Cpp/fost-cli/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/base/Cpp/fost-core-test/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/base/Cpp/fost-core/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/base/Cpp/fost-crypto/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/base/Cpp/fost-datetime/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/base/Cpp/fost-sinks/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/base/Cpp/fost-test/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/base/smoke_test.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/base/stress_test.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/CheckSymbolExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/FindThreads.cmake))

/Users/hotnow/TESTTHINGS/cpp/fost/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.12.3/bin/cmake -H/Users/hotnow/TESTTHINGS/cpp/src -B/Users/hotnow/TESTTHINGS/cpp/fost
