language: cpp
sudo: required
dist: xenial

notifications:
    webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

compiler:
    - gcc
    - clang

env:
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release

install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y ninja-build g++-8

script:
    - mkdir build.tmp && cd build.tmp
    - 'if [ "$CXX" = "g++" ]; then export CC=gcc-8; export CXX=g++-8; fi'
    - cp ../.travis.CMakeLists.txt CMakeLists.txt
    - cmake . -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -G Ninja
    - ninja
    - ninja check f5-cord-fuzz

