#!/usr/bin/env python3
import os
from os import path
from shlex import quote
import subprocess
import sys


def worked(execute, expected=0):
    print(' '.join([quote(c) for c in execute]))
    code = subprocess.call(execute)
    if not (code == expected):
        sys.exit(code)


COMPILER = {
    'clang++': [
        '-fdiagnostics-show-option',
        '-Wno-gnu-string-literal-operator-template',
        '-Wno-unused-const-variable',
    ],
    'g++': [
        '-fdiagnostics-show-option',
        '-Wno-gnu-string-literal-operator-template',
        '-Wno-unused-variable',
    ],
}
def compile(command, expected=0, fn=None):
    for compiler in sys.argv[1:] or ['clang++', 'g++']:
        extras = []
        for cxx, opts in COMPILER.items():
            if cxx in compiler:
                extras += opts
        execute = [compiler] + command + extras
        worked(execute, expected)
        if fn: fn()


CPP_OPTS = ['-Iinclude', '-Werror', '-Wall', '-Wextra', '-Wpedantic']

if __name__ == "__main__":
    for std in ['-std=c++14', '-std=c++1z']:
        folder = 'test/headers'
        for fname in os.listdir(folder):
            if fname == "CMakeLists.txt": continue
            execute = CPP_OPTS + [std] + ['-fsyntax-only', path.join(folder, fname)]
            compile(execute)

        folder = 'test/compile'
        for fname in os.listdir(folder):
            if fname == "CMakeLists.txt": continue
            execute = CPP_OPTS + [std] + ['-fsyntax-only', path.join(folder, fname)]
            compile(execute)

        folder = 'test/run'
        for fname in os.listdir(folder):
            if fname == "CMakeLists.txt": continue
            execute = CPP_OPTS + [std] + ['-o', '/tmp/a.out', path.join(folder, fname)]
            compile(execute, fn=lambda: worked(['/tmp/a.out']))
