# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/threading/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/threading/test/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/threading/test/headers/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hotnow/TESTTHINGS/cpp/src/fost/threading/test/run/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/CMakeConfigurableFile.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/CheckIncludeFile.c.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/CheckSymbolExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/FindThreads.cmake))

/Users/hotnow/TESTTHINGS/cpp/fost/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.12.3/bin/cmake -H/Users/hotnow/TESTTHINGS/cpp/src -B/Users/hotnow/TESTTHINGS/cpp/fost
